### PR TITLE
Update to 0.13 for test cases

### PR DESCRIPTION
**Pull request by cam-stitt**
Updating the terraform-json generated tests to use 0.13. This will allow us to have a parse test for verifying that `depends_on` is output into the `plan.json`.

### CODE REVIEW

**Comment by mwhooker** [comment]
How big of a deal would it be to support a matrix of terraform versions? I feel like that would be the right approach here

**Comment by cam-stitt** [comment]
> How big of a deal would it be to support a matrix of terraform versions? I feel like that would be the right approach here

Like anything, it's possible. The key part with this is the fact that both 0.12 and 0.13 look for `plan.json`. Therefore we would need to subfolder each version to keep them isolated most likely.

**Comment by cam-stitt** [comment]
@mwhooker I've added the capability to define a 013 test case by prefixing it with `013`. The `make generate` command seems to have also made "changes" to all the other files, but think it's minimal.

**Comment by cam-stitt** [comment]
I agree, but at least for now this follows a similar pattern to that found in hashicorp/sentinel-terraform-testdata

**Pull request merged**
