### PR TITLE
action: Add GetType()

### PR DESCRIPTION
**Pull request by korosuke613**
ref #42

### CODE REVIEW

**Review by radeksimko — COMMENTED** [review]
I wonder if instead of introducing new action constants which don't actually exist (the JSON would never map directly to them), we could just introduce `String()` method for `Actions` which would relatedly also have a slightly more loose compatibility guarantees by definition?

Do you have any use case for this other than displaying it as human-readable text somewhere? If so - can you elaborate on that use case and why the existing `Actions` methods don't meet that use case?

btw. see also https://github.com/hashicorp/terraform-json/issues/14

**Comment by korosuke613** [comment]
I am writing code to validate the plan results. Therefore, I would like to get the Action type of each Actions programmatically.

I wanted to make the Action string type-safe by referencing it from terraform-json, so I wanted to add an Action type for the Action that did not exist in JSON. For example, if we get them as String() and compare them, we won't be able to notice if we typo them.
```go
if someAction.String() == "dastroy-before-create" {
    // typo destroy to dastroy, so it never enters here.
}
```
However, since the goal is to simply get the Action type, I can change the method to use the String() method.

**Comment by radeksimko** [comment]
Sorry for these extra questions, but I'd really like to make sure we're solving the problem with this PR and I feel like I don't fully understand the problem.

What is it that makes it difficult for you to use the existing methods such as `DestroyBeforeCreate()` in your context? I feel that these are even better positioned for the use case you outlined - validating plan results - but I may be missing an important detail here?

Can you share a snippet of code or explain what kind of plan validation do you wish to perform? I would think that catching/highlighting dangerous sequence of actions that involve destruction is possible using the existing methods, is it not?

**Comment by korosuke613** [comment]
Sorry, my answer was not good.

The program verifies the Action type, and if it fails, it outputs the ResourceChange.Address for each Action type to the user. Therefore, the following function(`getActionType()`, `getActions()`) is provided to get the Action type of each ResourceChange.

```go
package test

import (
	"encoding/json"
	"fmt"
	tfjson "github.com/hashicorp/terraform-json"
	"github.com/stretchr/testify/assert"
	"testing"
)

// getActionType is get the action type of tfjson.Actions.
func getActionType(actions *tfjson.Actions) string {
	switch {
	case actions.NoOp():
		return string(tfjson.ActionNoop)
	case actions.Create():
		return string(tfjson.ActionCreate)
	case actions.Read():
		return string(tfjson.ActionRead)
	case actions.Update():
		return string(tfjson.ActionUpdate)
	case actions.Delete():
		return string(tfjson.ActionDelete)
	case actions.CreateBeforeDestroy():
		return "create-before-destroy"
	case actions.DestroyBeforeCreate():
		return "destroy-before-create"
	case actions.Replace():
		return "replace"
	default:
		panic("detected a non-existent Action")
	}
}

// getActions is get the resources for each Action type from tfjson.ResourceChange.
func getActions(resourceChanges map[string]*tfjson.ResourceChange) map[string][]string {
	actions := map[string][]string{}
	for _, resource := range resourceChanges {
		action := getActionType(&resource.Change.Actions)
		if _, ok := actions[action]; ok {
			actions[action] = append(actions[action], resource.Address)
		} else {
			actions[action] = []string{resource.Address}
		}
	}

	return actions
}

// parsePlanJson is parse the json of the plan results output by `terraform show -json`.
func parsePlanJson(planFilePath string) (*tfjson.Plan, error) {
	planJson, err := ioutil.ReadFile(planFilePath)
	if err != nil {
		return nil, fmt.Errorf("fail open %v: %v", planFilePath, err)
	}

	plan := tfjson.Plan{}

	if err := json.Unmarshal(planJson, &plan); err != nil {
		return nil, fmt.Errorf("fail parse %v: %v", planFilePath, err)
	}

	return &plan, nil
}

func TestTerraformPlanExample(t *testing.T) {
	plan, err := parsePlanJson("./plan.json")
	if err != nil {
		assert.Fail(t, err.Error())
	}

	resourceChanges := getResourceChanges(plan)
	actions := getActions(resourceChanges)

	// deny delete resource
	for _, actionType := range []string{
		string(tfjson.ActionDelete),
	} {
		if _, ok := actions[actionType]; ok {
			prettyActions, _ := json.MarshalIndent(actions, "", "  ")
			assert.Fail(t, fmt.Errorf("found resource to %v. %v", actionType,  string(prettyActions)).Error())
		}
	}
}
```

example output
```
❯ go test
--- FAIL: TestTerraformPlanExample (0.00s)
    plan_test.go:29:
        	Error Trace:	plan_test.go:82
        	Error:      	found resource to create. {
        	            	  "create": [
        	            	    "module.file.archive_file.examples"
        	            	  ],
        	            	  "no-op": [
        	            	    "module.file.local_file.example",
        	            	    "module.file.local_file.example2"
        	            	  ]
        	            	}
        	Test:       	TestTerraformPlan
FAIL
exit status 1
FAIL	github.com/korosuke613/playground/terraform/plan-test	0.240s
```

It is true that the problem can be solved using existing methods such as DestroyBeforeCreate(). However, I have to write a function like the above in each repository. I tried to prepare our own library for this purpose, but I thought that Actions could have a function to easily get the type of action, so I proposed this issue.

However, this discussion has made me question whether it is necessary as a terraform-json feature... (Maybe it should be handled by the users...)

**Comment by radeksimko** [comment]
Thank you for providing that extra context - this is helpful.

The reason I am little hesitant to the current proposal of the new action constants is because they are in fact _sequences_ of actions and I think we shouldn't be mixing the two.

From your example it isn't clear to me why you need to put every single change into the map and _then_ do the filtering. I feel that is the main/only reason why you'd need a constant or something serializable that can be used as a key in that map.

Why can you not filter out only the unwanted changes and then print them out - which could be done using the existing methods such as `CreateBeforeDestroy()`? Is this because you'll present this as a dynamic choice at runtime somewhere, as opposed to the code/program itself being the artifact with its "hard-coded" rules?

Would it help you if we introduced a new method on `Actions` e.g. `Is(ActionSequence) bool` and some related `ActionSequence` constants, such as

 - `Noop`
 - `CreateOnly`
 - `ReadOnly`
 - `UpdateOnly`
 - `DeleteOnly`
 - `CreateBeforeDestroy`
 - `DestroyBeforeCreate`

Both `["create", "destroy"]` and `["destroy", "create"]` can btw. be represented as "replace", since `Replace()` is just a convenience method on top of `CreateBeforeDestroy()` and `DestroyBeforeCreate()`, so I don't think we need that one.

Additionally or alternatively we could also introduce `Contains(Action) bool` if you want to be able to filter based on individual action, wherever it is in the sequence.

**Comment by korosuke613** [comment]
Thanks for the kind reply. Sorry it took me so long to reply.

I'll think about it again based on your comment. And I'm going to create the Issue again, so I'll close this pull request and the corresponding Issue once.

Thank you for your support!

**Pull request closed without merging**
